// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/cluster.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines a single job in a TensorFlow cluster.
type JobDef struct {
	// The name of this job.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapping from task ID to "hostname:port" string.
	//
	// If the `name` field contains "worker", and the `tasks` map contains a
	// mapping from 7 to "example.org:2222", then the device prefix
	// "/job:worker/task:7" will be assigned to "example.org:2222".
	Tasks                map[int32]string `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JobDef) Reset()         { *m = JobDef{} }
func (m *JobDef) String() string { return proto.CompactTextString(m) }
func (*JobDef) ProtoMessage()    {}
func (*JobDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea47a9615190cff, []int{0}
}

func (m *JobDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDef.Unmarshal(m, b)
}
func (m *JobDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDef.Marshal(b, m, deterministic)
}
func (m *JobDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDef.Merge(m, src)
}
func (m *JobDef) XXX_Size() int {
	return xxx_messageInfo_JobDef.Size(m)
}
func (m *JobDef) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDef.DiscardUnknown(m)
}

var xxx_messageInfo_JobDef proto.InternalMessageInfo

func (m *JobDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobDef) GetTasks() map[int32]string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// Defines a TensorFlow cluster as a set of jobs.
type ClusterDef struct {
	// The jobs that comprise the cluster.
	Job                  []*JobDef `protobuf:"bytes,1,rep,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ClusterDef) Reset()         { *m = ClusterDef{} }
func (m *ClusterDef) String() string { return proto.CompactTextString(m) }
func (*ClusterDef) ProtoMessage()    {}
func (*ClusterDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea47a9615190cff, []int{1}
}

func (m *ClusterDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterDef.Unmarshal(m, b)
}
func (m *ClusterDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterDef.Marshal(b, m, deterministic)
}
func (m *ClusterDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterDef.Merge(m, src)
}
func (m *ClusterDef) XXX_Size() int {
	return xxx_messageInfo_ClusterDef.Size(m)
}
func (m *ClusterDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterDef.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterDef proto.InternalMessageInfo

func (m *ClusterDef) GetJob() []*JobDef {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*JobDef)(nil), "tensorflow.JobDef")
	proto.RegisterMapType((map[int32]string)(nil), "tensorflow.JobDef.TasksEntry")
	proto.RegisterType((*ClusterDef)(nil), "tensorflow.ClusterDef")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/cluster.proto", fileDescriptor_8ea47a9615190cff)
}

var fileDescriptor_8ea47a9615190cff = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x13, 0x53, 0x70, 0x44, 0x90, 0xc5, 0x43, 0x28, 0x08, 0xa5, 0x88, 0xf4, 0xb4, 0x81,
	0xe6, 0x52, 0x3c, 0x56, 0xbd, 0x78, 0x2a, 0xc1, 0x93, 0xb7, 0x6c, 0x9c, 0xc4, 0xd8, 0x24, 0x23,
	0xbb, 0xb3, 0x4a, 0xbf, 0xc1, 0x1f, 0xf6, 0x28, 0xbb, 0x11, 0x52, 0xd0, 0xdb, 0xdb, 0x79, 0x33,
	0xef, 0xbd, 0x7d, 0x70, 0xc3, 0x38, 0x58, 0x32, 0x75, 0x47, 0x9f, 0x59, 0x45, 0x06, 0xb3, 0x77,
	0x43, 0x4c, 0xda, 0xd5, 0x59, 0xd5, 0x39, 0xcb, 0x68, 0x54, 0x18, 0x48, 0x98, 0xf6, 0x96, 0x5f,
	0x02, 0x66, 0x8f, 0xa4, 0xef, 0xb1, 0x96, 0x12, 0x4e, 0x86, 0xb2, 0xc7, 0x54, 0x2c, 0xc4, 0xea,
	0xb4, 0x08, 0x58, 0xe6, 0x90, 0x70, 0x69, 0xf7, 0x36, 0x8d, 0x16, 0xf1, 0xea, 0x6c, 0x7d, 0xa5,
	0xa6, 0x53, 0x35, 0x9e, 0xa9, 0x27, 0xcf, 0x3f, 0x0c, 0x6c, 0x0e, 0xc5, 0xb8, 0x3b, 0xdf, 0x00,
	0x4c, 0x43, 0x79, 0x01, 0xf1, 0x1e, 0x0f, 0x41, 0x35, 0x29, 0x3c, 0x94, 0x97, 0x90, 0x7c, 0x94,
	0x9d, 0xc3, 0x34, 0x0a, 0x4e, 0xe3, 0xe3, 0x36, 0xda, 0x88, 0xe5, 0x1a, 0xe0, 0x6e, 0x8c, 0xea,
	0x03, 0x5d, 0x43, 0xfc, 0x46, 0x3a, 0x15, 0xc1, 0x5a, 0xfe, 0xb5, 0x2e, 0x3c, 0xbd, 0x45, 0x98,
	0x93, 0x69, 0x8e, 0xd9, 0x97, 0xd6, 0xb2, 0x71, 0x03, 0xb7, 0x3d, 0x6e, 0xcf, 0x7f, 0xf5, 0x76,
	0xfe, 0xe7, 0x76, 0x27, 0x9e, 0xf3, 0xa6, 0xe5, 0x57, 0xa7, 0x55, 0x45, 0x7d, 0x76, 0xd4, 0xd7,
	0xff, 0xb0, 0xa1, 0x50, 0xe4, 0xb7, 0x10, 0x7a, 0x16, 0xba, 0xcb, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x68, 0x5a, 0xbd, 0x41, 0x65, 0x01, 0x00, 0x00,
}
