// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/trackable_object_graph.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrackableObjectGraph struct {
	Nodes                []*TrackableObjectGraph_TrackableObject `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *TrackableObjectGraph) Reset()         { *m = TrackableObjectGraph{} }
func (m *TrackableObjectGraph) String() string { return proto.CompactTextString(m) }
func (*TrackableObjectGraph) ProtoMessage()    {}
func (*TrackableObjectGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_120a5309f807e789, []int{0}
}

func (m *TrackableObjectGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackableObjectGraph.Unmarshal(m, b)
}
func (m *TrackableObjectGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackableObjectGraph.Marshal(b, m, deterministic)
}
func (m *TrackableObjectGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackableObjectGraph.Merge(m, src)
}
func (m *TrackableObjectGraph) XXX_Size() int {
	return xxx_messageInfo_TrackableObjectGraph.Size(m)
}
func (m *TrackableObjectGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackableObjectGraph.DiscardUnknown(m)
}

var xxx_messageInfo_TrackableObjectGraph proto.InternalMessageInfo

func (m *TrackableObjectGraph) GetNodes() []*TrackableObjectGraph_TrackableObject {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type TrackableObjectGraph_TrackableObject struct {
	// Objects which this object depends on.
	Children []*TrackableObjectGraph_TrackableObject_ObjectReference `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	// Serialized data specific to this object.
	Attributes []*TrackableObjectGraph_TrackableObject_SerializedTensor `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// Slot variables owned by this object.
	SlotVariables        []*TrackableObjectGraph_TrackableObject_SlotVariableReference `protobuf:"bytes,3,rep,name=slot_variables,json=slotVariables,proto3" json:"slot_variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                      `json:"-"`
	XXX_unrecognized     []byte                                                        `json:"-"`
	XXX_sizecache        int32                                                         `json:"-"`
}

func (m *TrackableObjectGraph_TrackableObject) Reset()         { *m = TrackableObjectGraph_TrackableObject{} }
func (m *TrackableObjectGraph_TrackableObject) String() string { return proto.CompactTextString(m) }
func (*TrackableObjectGraph_TrackableObject) ProtoMessage()    {}
func (*TrackableObjectGraph_TrackableObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_120a5309f807e789, []int{0, 0}
}

func (m *TrackableObjectGraph_TrackableObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject.Unmarshal(m, b)
}
func (m *TrackableObjectGraph_TrackableObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject.Marshal(b, m, deterministic)
}
func (m *TrackableObjectGraph_TrackableObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject.Merge(m, src)
}
func (m *TrackableObjectGraph_TrackableObject) XXX_Size() int {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject.Size(m)
}
func (m *TrackableObjectGraph_TrackableObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject.DiscardUnknown(m)
}

var xxx_messageInfo_TrackableObjectGraph_TrackableObject proto.InternalMessageInfo

func (m *TrackableObjectGraph_TrackableObject) GetChildren() []*TrackableObjectGraph_TrackableObject_ObjectReference {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *TrackableObjectGraph_TrackableObject) GetAttributes() []*TrackableObjectGraph_TrackableObject_SerializedTensor {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *TrackableObjectGraph_TrackableObject) GetSlotVariables() []*TrackableObjectGraph_TrackableObject_SlotVariableReference {
	if m != nil {
		return m.SlotVariables
	}
	return nil
}

type TrackableObjectGraph_TrackableObject_ObjectReference struct {
	// An index into `TrackableObjectGraph.nodes`, indicating the object
	// being referenced.
	NodeId int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// A user-provided name for the edge.
	LocalName            string   `protobuf:"bytes,2,opt,name=local_name,json=localName,proto3" json:"local_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackableObjectGraph_TrackableObject_ObjectReference) Reset() {
	*m = TrackableObjectGraph_TrackableObject_ObjectReference{}
}
func (m *TrackableObjectGraph_TrackableObject_ObjectReference) String() string {
	return proto.CompactTextString(m)
}
func (*TrackableObjectGraph_TrackableObject_ObjectReference) ProtoMessage() {}
func (*TrackableObjectGraph_TrackableObject_ObjectReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_120a5309f807e789, []int{0, 0, 0}
}

func (m *TrackableObjectGraph_TrackableObject_ObjectReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference.Unmarshal(m, b)
}
func (m *TrackableObjectGraph_TrackableObject_ObjectReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference.Marshal(b, m, deterministic)
}
func (m *TrackableObjectGraph_TrackableObject_ObjectReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference.Merge(m, src)
}
func (m *TrackableObjectGraph_TrackableObject_ObjectReference) XXX_Size() int {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference.Size(m)
}
func (m *TrackableObjectGraph_TrackableObject_ObjectReference) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference.DiscardUnknown(m)
}

var xxx_messageInfo_TrackableObjectGraph_TrackableObject_ObjectReference proto.InternalMessageInfo

func (m *TrackableObjectGraph_TrackableObject_ObjectReference) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *TrackableObjectGraph_TrackableObject_ObjectReference) GetLocalName() string {
	if m != nil {
		return m.LocalName
	}
	return ""
}

type TrackableObjectGraph_TrackableObject_SerializedTensor struct {
	// A name for the Tensor. Simple variables have only one
	// `SerializedTensor` named "VARIABLE_VALUE" by convention. This value may
	// be restored on object creation as an optimization.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The full name of the variable/tensor, if applicable. Used to allow
	// name-based loading of checkpoints which were saved using an
	// object-based API. Should match the checkpoint key which would have been
	// assigned by tf.train.Saver.
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// The generated name of the Tensor in the checkpoint.
	CheckpointKey string `protobuf:"bytes,3,opt,name=checkpoint_key,json=checkpointKey,proto3" json:"checkpoint_key,omitempty"`
	// Whether checkpoints should be considered as matching even without this
	// value restored. Used for non-critical values which don't affect the
	// TensorFlow graph, such as layer configurations.
	OptionalRestore      bool     `protobuf:"varint,4,opt,name=optional_restore,json=optionalRestore,proto3" json:"optional_restore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) Reset() {
	*m = TrackableObjectGraph_TrackableObject_SerializedTensor{}
}
func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) String() string {
	return proto.CompactTextString(m)
}
func (*TrackableObjectGraph_TrackableObject_SerializedTensor) ProtoMessage() {}
func (*TrackableObjectGraph_TrackableObject_SerializedTensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_120a5309f807e789, []int{0, 0, 1}
}

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor.Unmarshal(m, b)
}
func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor.Marshal(b, m, deterministic)
}
func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor.Merge(m, src)
}
func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) XXX_Size() int {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor.Size(m)
}
func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor.DiscardUnknown(m)
}

var xxx_messageInfo_TrackableObjectGraph_TrackableObject_SerializedTensor proto.InternalMessageInfo

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) GetCheckpointKey() string {
	if m != nil {
		return m.CheckpointKey
	}
	return ""
}

func (m *TrackableObjectGraph_TrackableObject_SerializedTensor) GetOptionalRestore() bool {
	if m != nil {
		return m.OptionalRestore
	}
	return false
}

type TrackableObjectGraph_TrackableObject_SlotVariableReference struct {
	// An index into `TrackableObjectGraph.nodes`, indicating the
	// variable object this slot was created for.
	OriginalVariableNodeId int32 `protobuf:"varint,1,opt,name=original_variable_node_id,json=originalVariableNodeId,proto3" json:"original_variable_node_id,omitempty"`
	// The name of the slot (e.g. "m"/"v").
	SlotName string `protobuf:"bytes,2,opt,name=slot_name,json=slotName,proto3" json:"slot_name,omitempty"`
	// An index into `TrackableObjectGraph.nodes`, indicating the
	// `Object` with the value of the slot variable.
	SlotVariableNodeId   int32    `protobuf:"varint,3,opt,name=slot_variable_node_id,json=slotVariableNodeId,proto3" json:"slot_variable_node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) Reset() {
	*m = TrackableObjectGraph_TrackableObject_SlotVariableReference{}
}
func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) String() string {
	return proto.CompactTextString(m)
}
func (*TrackableObjectGraph_TrackableObject_SlotVariableReference) ProtoMessage() {}
func (*TrackableObjectGraph_TrackableObject_SlotVariableReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_120a5309f807e789, []int{0, 0, 2}
}

func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference.Unmarshal(m, b)
}
func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference.Marshal(b, m, deterministic)
}
func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference.Merge(m, src)
}
func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) XXX_Size() int {
	return xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference.Size(m)
}
func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference.DiscardUnknown(m)
}

var xxx_messageInfo_TrackableObjectGraph_TrackableObject_SlotVariableReference proto.InternalMessageInfo

func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) GetOriginalVariableNodeId() int32 {
	if m != nil {
		return m.OriginalVariableNodeId
	}
	return 0
}

func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) GetSlotName() string {
	if m != nil {
		return m.SlotName
	}
	return ""
}

func (m *TrackableObjectGraph_TrackableObject_SlotVariableReference) GetSlotVariableNodeId() int32 {
	if m != nil {
		return m.SlotVariableNodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*TrackableObjectGraph)(nil), "tensorflow.TrackableObjectGraph")
	proto.RegisterType((*TrackableObjectGraph_TrackableObject)(nil), "tensorflow.TrackableObjectGraph.TrackableObject")
	proto.RegisterType((*TrackableObjectGraph_TrackableObject_ObjectReference)(nil), "tensorflow.TrackableObjectGraph.TrackableObject.ObjectReference")
	proto.RegisterType((*TrackableObjectGraph_TrackableObject_SerializedTensor)(nil), "tensorflow.TrackableObjectGraph.TrackableObject.SerializedTensor")
	proto.RegisterType((*TrackableObjectGraph_TrackableObject_SlotVariableReference)(nil), "tensorflow.TrackableObjectGraph.TrackableObject.SlotVariableReference")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/trackable_object_graph.proto", fileDescriptor_120a5309f807e789)
}

var fileDescriptor_120a5309f807e789 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x86, 0xc9, 0x76, 0x5b, 0xdb, 0x23, 0xbb, 0x5d, 0x82, 0xab, 0x63, 0x17, 0xa1, 0x08, 0x42,
	0xbd, 0x99, 0xaa, 0x8b, 0xa0, 0x77, 0xea, 0xc5, 0xca, 0x22, 0xac, 0x30, 0x2e, 0x5e, 0x88, 0x10,
	0x32, 0x99, 0xd3, 0x36, 0x36, 0x9d, 0x53, 0x92, 0x54, 0x59, 0xdf, 0xc3, 0x17, 0xf0, 0xd2, 0x37,
	0xf1, 0x8d, 0xbc, 0x94, 0xa4, 0x9d, 0xed, 0xb4, 0xf4, 0xa6, 0x77, 0x33, 0x7f, 0xfe, 0xff, 0x0b,
	0xff, 0x09, 0x07, 0x5e, 0x7a, 0x2c, 0x1d, 0xd9, 0x91, 0xa1, 0x1f, 0x43, 0x45, 0x16, 0x87, 0x73,
	0x4b, 0x9e, 0xf2, 0xc5, 0x68, 0xe8, 0xad, 0x54, 0x53, 0x99, 0x1b, 0x14, 0x94, 0x7f, 0x43, 0xe5,
	0xc5, 0xd8, 0xca, 0xf9, 0x24, 0x8d, 0xe7, 0x1c, 0xd6, 0xb1, 0xc7, 0x7f, 0x5a, 0x70, 0xef, 0xba,
	0x32, 0x7f, 0x8c, 0xde, 0xf7, 0xc1, 0xca, 0x2f, 0xa0, 0x59, 0x52, 0x81, 0x2e, 0x61, 0xfd, 0xc6,
	0xe0, 0xee, 0x8b, 0x67, 0xe9, 0x3a, 0x94, 0xee, 0x0a, 0x6c, 0x8b, 0xd9, 0x32, 0xde, 0xfb, 0xdb,
	0x84, 0xee, 0xd6, 0x11, 0xff, 0x0a, 0x6d, 0x35, 0xd1, 0xa6, 0xb0, 0x58, 0xae, 0xf0, 0x6f, 0xf6,
	0xc5, 0xa7, 0xab, 0x5b, 0x70, 0x84, 0x16, 0x4b, 0x85, 0xd9, 0x2d, 0x91, 0x4b, 0x00, 0xe9, 0xbd,
	0xd5, 0xf9, 0xc2, 0xa3, 0x4b, 0x0e, 0x22, 0xff, 0xed, 0xde, 0xfc, 0x4f, 0x68, 0xb5, 0x34, 0xfa,
	0x27, 0x16, 0xd7, 0x31, 0x99, 0xd5, 0xa0, 0x7c, 0x06, 0xc7, 0xce, 0x90, 0x17, 0xdf, 0xa5, 0xd5,
	0x21, 0xe3, 0x92, 0x46, 0xbc, 0xe6, 0x62, 0xff, 0x6b, 0x0c, 0xf9, 0xcf, 0x2b, 0xca, 0xba, 0xcc,
	0x91, 0xab, 0xc9, 0xae, 0x77, 0x09, 0xdd, 0xad, 0xba, 0xfc, 0x01, 0xdc, 0x09, 0xf3, 0x15, 0xba,
	0x48, 0x58, 0x9f, 0x0d, 0x9a, 0x59, 0x2b, 0xfc, 0x5e, 0x16, 0xfc, 0x11, 0x80, 0x21, 0x25, 0x8d,
	0x28, 0xe5, 0x0c, 0x93, 0x83, 0x3e, 0x1b, 0x74, 0xb2, 0x4e, 0x54, 0xae, 0xe4, 0x0c, 0x7b, 0xbf,
	0x18, 0x9c, 0x6c, 0x57, 0xe3, 0x1c, 0x0e, 0xa3, 0x9b, 0x45, 0x77, 0xfc, 0xe6, 0x67, 0xd0, 0x19,
	0x2d, 0xcc, 0x06, 0xa6, 0x1d, 0x84, 0x40, 0xe1, 0x4f, 0xe0, 0x58, 0x4d, 0x50, 0x4d, 0xe7, 0xa4,
	0x4b, 0x2f, 0xa6, 0x78, 0x93, 0x34, 0xa2, 0xe3, 0x68, 0xad, 0x7e, 0xc0, 0x1b, 0xfe, 0x14, 0x4e,
	0x68, 0xee, 0x35, 0x95, 0xd2, 0x08, 0x8b, 0xce, 0x93, 0xc5, 0xe4, 0xb0, 0xcf, 0x06, 0xed, 0xac,
	0x5b, 0xe9, 0xd9, 0x52, 0xee, 0xfd, 0x66, 0x70, 0xba, 0x73, 0x16, 0xfc, 0x35, 0x3c, 0x24, 0xab,
	0xc7, 0x3a, 0x40, 0xaa, 0x79, 0x8b, 0xcd, 0xee, 0xf7, 0x2b, 0x43, 0x95, 0xbe, 0x5a, 0xce, 0xe2,
	0x0c, 0x3a, 0xf1, 0x99, 0xea, 0x1d, 0x82, 0x10, 0x3b, 0x3c, 0x87, 0xd3, 0x8d, 0x37, 0xbc, 0x65,
	0x36, 0x22, 0x93, 0xd7, 0x9f, 0x60, 0xc9, 0x7b, 0xf7, 0xea, 0xcb, 0xf9, 0x58, 0xfb, 0xc9, 0x22,
	0x4f, 0x15, 0xcd, 0x86, 0xb5, 0xe5, 0xdb, 0xfd, 0x39, 0xa6, 0xb8, 0x95, 0xff, 0x18, 0xcb, 0x5b,
	0x71, 0xf3, 0xce, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xf1, 0x8d, 0x9f, 0xb2, 0x03, 0x00,
	0x00,
}
