// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/verifier_config.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifierConfig_Toggle int32

const (
	VerifierConfig_DEFAULT VerifierConfig_Toggle = 0
	VerifierConfig_ON      VerifierConfig_Toggle = 1
	VerifierConfig_OFF     VerifierConfig_Toggle = 2
)

var VerifierConfig_Toggle_name = map[int32]string{
	0: "DEFAULT",
	1: "ON",
	2: "OFF",
}

var VerifierConfig_Toggle_value = map[string]int32{
	"DEFAULT": 0,
	"ON":      1,
	"OFF":     2,
}

func (x VerifierConfig_Toggle) String() string {
	return proto.EnumName(VerifierConfig_Toggle_name, int32(x))
}

func (VerifierConfig_Toggle) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5049fcf5d8bb3c3c, []int{0, 0}
}

// The config for graph verifiers.
type VerifierConfig struct {
	// Deadline for completion of all verification i.e. all the Toggle ON
	// verifiers must complete execution within this time.
	VerificationTimeoutInMs int64 `protobuf:"varint,1,opt,name=verification_timeout_in_ms,json=verificationTimeoutInMs,proto3" json:"verification_timeout_in_ms,omitempty"`
	// Perform structural validation on a tensorflow graph. Default is OFF.
	StructureVerifier    VerifierConfig_Toggle `protobuf:"varint,2,opt,name=structure_verifier,json=structureVerifier,proto3,enum=tensorflow.VerifierConfig_Toggle" json:"structure_verifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VerifierConfig) Reset()         { *m = VerifierConfig{} }
func (m *VerifierConfig) String() string { return proto.CompactTextString(m) }
func (*VerifierConfig) ProtoMessage()    {}
func (*VerifierConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5049fcf5d8bb3c3c, []int{0}
}

func (m *VerifierConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierConfig.Unmarshal(m, b)
}
func (m *VerifierConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierConfig.Marshal(b, m, deterministic)
}
func (m *VerifierConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierConfig.Merge(m, src)
}
func (m *VerifierConfig) XXX_Size() int {
	return xxx_messageInfo_VerifierConfig.Size(m)
}
func (m *VerifierConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierConfig proto.InternalMessageInfo

func (m *VerifierConfig) GetVerificationTimeoutInMs() int64 {
	if m != nil {
		return m.VerificationTimeoutInMs
	}
	return 0
}

func (m *VerifierConfig) GetStructureVerifier() VerifierConfig_Toggle {
	if m != nil {
		return m.StructureVerifier
	}
	return VerifierConfig_DEFAULT
}

func init() {
	proto.RegisterEnum("tensorflow.VerifierConfig_Toggle", VerifierConfig_Toggle_name, VerifierConfig_Toggle_value)
	proto.RegisterType((*VerifierConfig)(nil), "tensorflow.VerifierConfig")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/verifier_config.proto", fileDescriptor_5049fcf5d8bb3c3c)
}

var fileDescriptor_5049fcf5d8bb3c3c = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x4d, 0x07, 0x1d, 0x3c, 0x61, 0xd4, 0x20, 0x58, 0x3c, 0xcd, 0x1d, 0x64, 0xa7, 0x16,
	0xdc, 0xd1, 0x93, 0x53, 0x0b, 0x82, 0xba, 0x32, 0xaa, 0x07, 0x2f, 0x65, 0x2d, 0x49, 0x8c, 0xae,
	0x79, 0xf2, 0x92, 0xb8, 0x3f, 0xd1, 0x7f, 0xc9, 0xa3, 0xd8, 0x3a, 0xed, 0xc0, 0x5b, 0xe0, 0xf7,
	0x3d, 0xbe, 0xf0, 0x41, 0xe2, 0x84, 0xb1, 0x48, 0x72, 0x8d, 0x9b, 0xb4, 0x46, 0x12, 0xe9, 0x1b,
	0xa1, 0xc3, 0xca, 0xcb, 0xf4, 0x5d, 0x90, 0x96, 0x5a, 0x50, 0x59, 0xa3, 0x91, 0x5a, 0x25, 0xed,
	0xc0, 0xe1, 0x8f, 0x9f, 0x7c, 0x30, 0x18, 0x3d, 0xfe, 0x50, 0x97, 0x2d, 0xc4, 0xcf, 0xe1, 0xb8,
	0xbb, 0xab, 0x57, 0x4e, 0xa3, 0x29, 0x9d, 0x6e, 0x04, 0x7a, 0x57, 0x6a, 0x53, 0x36, 0x36, 0x66,
	0x63, 0x36, 0x1d, 0x2c, 0x8f, 0xfa, 0x44, 0xd1, 0x01, 0x37, 0xe6, 0xce, 0xf2, 0x1c, 0xb8, 0x75,
	0xe4, 0x6b, 0xe7, 0x49, 0x94, 0x5b, 0x7d, 0x1c, 0x8c, 0xd9, 0x74, 0x74, 0x76, 0xd2, 0xfb, 0x68,
	0xb2, 0x2b, 0x4d, 0x0a, 0x54, 0x6a, 0x2d, 0x96, 0x07, 0xbf, 0xc7, 0xdb, 0x7d, 0x72, 0x0a, 0x61,
	0x37, 0xf2, 0x7d, 0x18, 0x5e, 0x5d, 0x67, 0x17, 0x0f, 0xb7, 0x45, 0xb4, 0xc7, 0x43, 0x08, 0x16,
	0xf7, 0x11, 0xe3, 0x43, 0x18, 0x2c, 0xb2, 0x2c, 0x0a, 0xe6, 0x2f, 0x10, 0x23, 0xa9, 0xbe, 0x42,
	0xd2, 0xaa, 0x11, 0x1b, 0xa4, 0xd7, 0xf9, 0xe1, 0xae, 0x2d, 0xff, 0xce, 0x60, 0x73, 0xf6, 0x34,
	0x53, 0xda, 0x3d, 0xfb, 0x2a, 0xa9, 0xb1, 0x49, 0x7b, 0x11, 0xff, 0x7f, 0x2a, 0x6c, 0xeb, 0x7e,
	0x32, 0x56, 0x85, 0x6d, 0xc8, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x88, 0x50, 0xf4,
	0x7a, 0x01, 0x00, 0x00,
}
